version: '3.7'
services:

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dbDocument
    ports:
        - 27017:27017
    networks:
      - myNetwork
    volumes:
        - ./mongodb/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # Neo4j
  neo4j:
    build:
      context: neo4j/
    container_name: neo4j
    volumes:
      - ./neo4j/neo4j_database:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_auth__enabled=true
      - APOC_ES_URL=http://localhost:9200
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"

  # ElasticSearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - xpack.security.enabled=false
    volumes:
      - ./elasticSearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - myNetwork
    ports:
      - 9200:9200
      - 9300:9300

  # Kibana
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.6.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_ENCRYPTED_SAVED_OBJECTS_ENCRYPTION_KEY=sZsM9k6hBz8WL2QCQFwfQGxjKcJTdQMy
    networks:
      - myNetwork
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
      
networks:
  myNetwork:
